name: Notify MS Teams
on: 
  push:
    branches:
      - quality
      - stage
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github code
        uses: actions/checkout@v4
      - name: Fail Step
        run: exit 1
      - name: Pass Step
        run: echo "Passing step"
      - name: Notify Teams - Stage
        if: always() && (github.ref == 'refs/heads/stage') 
        uses: sergioaten/msteams-notifications@v0.1-beta
        with:
          webhook: ${{ secrets.MS_TEAMS_WEBHOOK }}
          steps: ${{ toJson(steps) }}
      - name: Notify Teams - Quality - Failure
        if: failure() && (github.ref == 'refs/heads/quality') 
        uses: sergioaten/msteams-notifications@v0.1-beta
        with:
          webhook: ${{ secrets.MS_TEAMS_WEBHOOK }}
          steps: ${{ toJson(steps) }}
